DEFAULT_OPTIMIZATION_CONFIG = {
    "t_inicio": 540.0,
    "cap_vol_cm3": 3_750_000.0,
    "cap_peso_g": 803_333.333333333,
    "factor_s": 1.0,
    "alpha_espera": 0.0,
    "costo_fijo_camion": 0.0,
    "ga_pop_size": 100,
    "ga_n_gen": 200,
    "ga_seed": 42,
    "d_max_min": 300.0,
    "max_vehiculos_globales": 20,
    "clustering_time_column": "a_ventana",
    "clustering_default_window_start_hour": 9,
    "clustering_alpha_time": 10.0,
    "clustering_eps": 0.3,
    "clustering_min_samples": 3,
    "clustering_rescue_threshold": 0.8,
    "force_outlier_rescue": True,
}
